# Generated by Django 3.2.2 on 2021-08-06 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groupmeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='related_group', through='groupmeet.UserGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
