# Generated by Django 3.2.2 on 2021-07-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupmeet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='joined',
            new_name='allowed',
        ),
    ]
