# Generated by Django 3.2.2 on 2021-08-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
